# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/go2/motion.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2_description/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

# PD Controller gains for quadruped joints (hip, thigh, calf) for each leg (FR, FL, RR, RL)
kps: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
kds: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

# Default standing pose joint angles
# Format: [FR_hip, FR_thigh, FR_calf, FL_hip, FL_thigh, FL_calf, RR_hip, RR_thigh, RR_calf, RL_hip, RL_thigh, RL_calf]
default_angles: [0.0, 0.8, -1.6, 0.0, 0.8, -1.6, 0.0, 0.8, -1.6, 0.0, 0.8, -1.6]

# Scaling factors for observations and actions
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25

# Command scaling factors (linear_x, linear_y, angular_yaw)
cmd_scale: [2.0, 2.0, 0.25]

# Dimensions for neural network
num_actions: 12  # 12 joints for a quadruped
num_obs: 48      # Observation space dimension

# Initial command velocities [lin_x, lin_y, ang_z]
cmd_init: [0.5, 0, 0]
